using System.Net;
using System.Net.Http.Json;
using po_prostu_silka.Domain;

namespace po_prostu_silka.Tests;

/// <summary>
/// Class occurrences built from class types (prd-v2 US-01, FR-008..FR-013).
///
/// <para>
/// WHY THIS FILE EXISTS. S-05 kept the FR-007 asymmetry safe structurally: <c>Class</c> had no
/// navigation to <c>ClassType</c>, so no write path could reach <c>DefaultCapacity</c> even by
/// accident. S-06 adds that navigation to make the read joins idiomatic, which removes the
/// compile-time barrier. The three copy-semantics tests below are the replacement: they are the only
/// thing standing between a future edit and a type change silently moving the capacity of a class
/// that already has bookings.
/// </para>
///
/// <para>
/// EVERY TEST TAKES ITS OWN TIME SLOT. The overlap rule is now club-wide (FR-012) rather than
/// room-scoped, so any two classes anywhere in the table can collide. Fixed times would make these
/// tests refuse each other instead of exercising the rule. <see cref="NextSlot"/> hands out slots 60
/// days apart, which leaves room for a three-week duplicate batch (+21 days) inside each one.
/// </para>
/// </summary>
[Collection(nameof(IntegrationCollection))]
public class ClassEndpointTests(IntegrationTestFixture fixture)
{
    /// <summary>Mirrors ScheduledClass.</summary>
    private sealed record ClassBody(
        Guid Id,
        Guid ClassTypeId,
        string Name,
        string? Description,
        DateTimeOffset StartsAt,
        int DurationMinutes,
        string InstructorUserId,
        string Instructor,
        int Capacity,
        int FreeSpots,
        string Status);

    /// <summary>Mirrors ClassTypeSummary — only what these tests read from it.</summary>
    private sealed record ClassTypeBody(
        Guid Id,
        string Name,
        string? Description,
        int DefaultDurationMinutes,
        int DefaultCapacity,
        bool IsActive);

    /// <summary>Mirrors DuplicateResult.</summary>
    private sealed record DuplicateBody(int Created, int[] SkippedWeeks);

    /// <summary>Mirrors MemberSummary — only what these tests read from it.</summary>
    private sealed record MemberBody(string Id, string Email, string DisplayName, string Status);

    /// <summary>Mirrors TrainerSummary.</summary>
    private sealed record TrainerBody(string Id, string DisplayName);

    private sealed record FailureBody(string Reason);

    private const string Endpoint = "/api/admin/classes";
    private const string TypesEndpoint = "/api/admin/class-types";

    /// <summary>
    /// Slot allocator. June 2030 rather than "now + something": a fixed base keeps a failing test
    /// reproducible, and it is far enough ahead that the create-only starts_in_past rule never fires.
    /// 60-day spacing leaves each test's duplicate batch room to run without reaching the next slot.
    /// </summary>
    private static int _slot;

    private static DateTimeOffset NextSlot() =>
        new DateTimeOffset(2030, 6, 1, 10, 0, 0, TimeSpan.Zero)
            .AddDays(60 * Interlocked.Increment(ref _slot));

    private static string UniqueEmail(string prefix) => $"{prefix}-{Guid.NewGuid():N}@test.local";

    private static string UniqueName() => $"Joga-{Guid.NewGuid():N}";

    private static object Request(
        Guid classTypeId,
        DateTimeOffset startsAt,
        string instructorUserId,
        int duration = 60,
        int capacity = 12) =>
        new
        {
            classTypeId,
            startsAt,
            instructorUserId,
            durationMinutes = duration,
            capacity,
        };

    // --- fixture helpers -------------------------------------------------------

    private async Task<HttpClient> AdminAsync() =>
        await fixture.CreateAuthenticatedClientAsync(TestUsers.ActiveAdminEmail);

    private static async Task<ClassTypeBody> CreateTypeAsync(
        HttpClient admin, int duration = 60, int capacity = 12)
    {
        var response = await admin.PostAsJsonAsync(TypesEndpoint, new
        {
            name = UniqueName(),
            description = (string?)"Opis",
            defaultDurationMinutes = duration,
            defaultCapacity = capacity,
        });

        Assert.Equal(HttpStatusCode.OK, response.StatusCode);
        return (await response.Content.ReadFromJsonAsync<ClassTypeBody>())!;
    }

    /// <summary>
    /// Creates an account and returns its id, looked up through the admin member list — the id is
    /// generated by Identity and there is no other way for a test to learn it.
    /// </summary>
    private async Task<string> CreateAccountAsync(
        HttpClient admin, AccountStatus status, string role, string? displayName = null)
    {
        var email = UniqueEmail(role.ToLowerInvariant());
        await fixture.CreateUserAsync(email, status, role, displayName);

        var members = await admin.GetFromJsonAsync<List<MemberBody>>("/api/admin/members");

        return members!.Single(m => m.Email == email).Id;
    }

    private Task<string> CreateTrainerAsync(HttpClient admin, string? displayName = null) =>
        CreateAccountAsync(admin, AccountStatus.Active, ApplicationRoles.Trainer, displayName);

    /// <summary>An admin, an active type and an active trainer — what almost every test below needs.</summary>
    private async Task<(HttpClient Admin, ClassTypeBody Type, string TrainerId)> ArrangeAsync(
        int duration = 60, int capacity = 12)
    {
        var admin = await AdminAsync();
        var type = await CreateTypeAsync(admin, duration, capacity);
        var trainerId = await CreateTrainerAsync(admin);

        return (admin, type, trainerId);
    }

    private static async Task<ClassBody> PostClassAsync(
        HttpClient admin,
        Guid typeId,
        DateTimeOffset startsAt,
        string trainerId,
        int duration = 60,
        int capacity = 12)
    {
        var response = await admin.PostAsJsonAsync(
            Endpoint, Request(typeId, startsAt, trainerId, duration, capacity));

        Assert.Equal(HttpStatusCode.OK, response.StatusCode);
        return (await response.Content.ReadFromJsonAsync<ClassBody>())!;
    }

    // --- who may reach the group ----------------------------------------------

    public static TheoryData<string, string> EveryAdminRoute => new()
    {
        { "GET", Endpoint },
        { "GET", $"{Endpoint}/{Guid.Empty}" },
        { "POST", Endpoint },
        { "PUT", $"{Endpoint}/{Guid.Empty}" },
        { "DELETE", $"{Endpoint}/{Guid.Empty}" },
        { "POST", $"{Endpoint}/{Guid.Empty}/duplicate" },
        { "GET", "/api/admin/trainers" },
    };

    [Theory]
    [MemberData(nameof(EveryAdminRoute))]
    public async Task Admin_routes_refuse_a_member(string method, string route)
    {
        var member = await fixture.CreateAuthenticatedClientAsync(TestUsers.ActiveMemberEmail);

        var response = await member.SendAsync(
            new HttpRequestMessage(new HttpMethod(method), route)
            {
                Content = JsonContent.Create(new { }),
            });

        Assert.Equal(HttpStatusCode.Forbidden, response.StatusCode);
    }

    // --- FR-007: identity by reference, numbers by copy -----------------------
    //
    // The three tests that replace the compile-time barrier. Read the class remarks before touching
    // them.

    [Fact]
    public async Task Create_copies_the_capacity_from_the_request_not_the_type()
    {
        // The type says 12; the admin overrode it to 8 for this session (FR-008).
        var (admin, type, trainerId) = await ArrangeAsync(capacity: 12);

        var created = await PostClassAsync(
            admin, type.Id, NextSlot(), trainerId, duration: 45, capacity: 8);

        Assert.Equal(8, created.Capacity);
        Assert.Equal(45, created.DurationMinutes);

        // And it is the stored value, not just what the create response echoed back.
        var reread = await admin.GetFromJsonAsync<ClassBody>($"{Endpoint}/{created.Id}");
        Assert.Equal(8, reread!.Capacity);
        Assert.Equal(45, reread.DurationMinutes);
    }

    [Fact]
    public async Task Editing_the_type_does_not_move_an_existing_occurrences_capacity()
    {
        // THE ONE THAT MATTERS. Capacity resolved through the type would let this edit change the
        // value the no-overbooking guarantee is checked against, on a class that may already have
        // bookings.
        var (admin, type, trainerId) = await ArrangeAsync(capacity: 12);
        var created = await PostClassAsync(admin, type.Id, NextSlot(), trainerId, capacity: 12);

        var edit = await admin.PutAsJsonAsync($"{TypesEndpoint}/{type.Id}", new
        {
            name = type.Name,
            description = type.Description,
            defaultDurationMinutes = 90,
            defaultCapacity = 200,
        });

        Assert.Equal(HttpStatusCode.OK, edit.StatusCode);

        var reread = await admin.GetFromJsonAsync<ClassBody>($"{Endpoint}/{created.Id}");

        Assert.Equal(12, reread!.Capacity);
        Assert.Equal(60, reread.DurationMinutes);
    }

    [Fact]
    public async Task Renaming_the_type_renames_an_existing_occurrence()
    {
        // The other half of the asymmetry: identity DOES resolve by reference, which is the whole
        // reason class types exist (FR-007, FR-010).
        var (admin, type, trainerId) = await ArrangeAsync();
        var created = await PostClassAsync(admin, type.Id, NextSlot(), trainerId);

        Assert.Equal(type.Name, created.Name);

        var renamed = UniqueName();
        var edit = await admin.PutAsJsonAsync($"{TypesEndpoint}/{type.Id}", new
        {
            name = renamed,
            description = (string?)"Nowy opis",
            defaultDurationMinutes = type.DefaultDurationMinutes,
            defaultCapacity = type.DefaultCapacity,
        });

        Assert.Equal(HttpStatusCode.OK, edit.StatusCode);

        var reread = await admin.GetFromJsonAsync<ClassBody>($"{Endpoint}/{created.Id}");

        Assert.Equal(renamed, reread!.Name);
        Assert.Equal("Nowy opis", reread.Description);
    }

    // --- FR-012: one club, one class at a time --------------------------------

    [Fact]
    public async Task Create_refuses_a_time_that_overlaps_any_other_class()
    {
        var (admin, type, trainerId) = await ArrangeAsync();
        var slot = NextSlot();

        await PostClassAsync(admin, type.Id, slot, trainerId, duration: 60);

        // A DIFFERENT type and a DIFFERENT trainer: the rule is club-wide, not per-type. Overlapping
        // by 30 minutes rather than starting together, so the interval arithmetic is what refuses it.
        var otherType = await CreateTypeAsync(admin);
        var otherTrainer = await CreateTrainerAsync(admin);

        var response = await admin.PostAsJsonAsync(
            Endpoint, Request(otherType.Id, slot.AddMinutes(30), otherTrainer));

        Assert.Equal(HttpStatusCode.Conflict, response.StatusCode);
        Assert.Equal("time_conflict", (await response.Content.ReadFromJsonAsync<FailureBody>())!.Reason);
    }

    [Fact]
    public async Task Back_to_back_classes_do_not_conflict()
    {
        // Half-open intervals: a class ending exactly when the next begins is legal, and a club runs
        // its timetable that way.
        var (admin, type, trainerId) = await ArrangeAsync();
        var slot = NextSlot();

        await PostClassAsync(admin, type.Id, slot, trainerId, duration: 60);

        var response = await admin.PostAsJsonAsync(
            Endpoint, Request(type.Id, slot.AddMinutes(60), trainerId));

        Assert.Equal(HttpStatusCode.OK, response.StatusCode);
    }

    [Fact]
    public async Task Edit_refuses_a_time_that_overlaps_but_not_the_classs_own_time()
    {
        var (admin, type, trainerId) = await ArrangeAsync();
        var slot = NextSlot();

        var first = await PostClassAsync(admin, type.Id, slot, trainerId);
        var second = await PostClassAsync(admin, type.Id, slot.AddHours(3), trainerId);

        // Keeping its own time must NOT count as conflicting with itself.
        var unchanged = await admin.PutAsJsonAsync(
            $"{Endpoint}/{second.Id}", Request(type.Id, slot.AddHours(3), trainerId, capacity: 15));

        Assert.Equal(HttpStatusCode.OK, unchanged.StatusCode);

        // Moving it onto the first one must.
        var moved = await admin.PutAsJsonAsync(
            $"{Endpoint}/{second.Id}", Request(type.Id, first.StartsAt, trainerId));

        Assert.Equal(HttpStatusCode.Conflict, moved.StatusCode);
        Assert.Equal("time_conflict", (await moved.Content.ReadFromJsonAsync<FailureBody>())!.Reason);
    }

    // --- FR-013: duplication still succeeds partially -------------------------

    [Fact]
    public async Task Duplicate_skips_and_reports_the_colliding_week_and_creates_the_rest()
    {
        var (admin, type, trainerId) = await ArrangeAsync();
        var slot = NextSlot();

        var source = await PostClassAsync(admin, type.Id, slot, trainerId);

        // Plant a collision exactly where week 2 would land.
        await PostClassAsync(admin, type.Id, slot.AddDays(14), trainerId);

        var response = await admin.PostAsJsonAsync($"{Endpoint}/{source.Id}/duplicate", new { weeks = 3 });

        Assert.Equal(HttpStatusCode.OK, response.StatusCode);

        var result = (await response.Content.ReadFromJsonAsync<DuplicateBody>())!;

        Assert.Equal(2, result.Created);
        Assert.Equal([2], result.SkippedWeeks);

        // The copies are real, and they carry the source's references and numbers.
        var admin_list = await admin.GetFromJsonAsync<List<ClassBody>>(Endpoint);
        var copies = admin_list!
            .Where(c => c.ClassTypeId == type.Id && c.Id != source.Id)
            .ToList();

        // Weeks 1 and 3, plus the collision we planted.
        Assert.Equal(3, copies.Count);
        Assert.All(copies, c => Assert.Equal(trainerId, c.InstructorUserId));
        Assert.All(copies, c => Assert.Equal(source.Capacity, c.Capacity));
    }

    // --- FR-006 / FR-008: the type reference ----------------------------------

    [Fact]
    public async Task Create_refuses_an_unknown_or_inactive_type()
    {
        var (admin, type, trainerId) = await ArrangeAsync();

        var unknown = await admin.PostAsJsonAsync(
            Endpoint, Request(Guid.NewGuid(), NextSlot(), trainerId));

        Assert.Equal(HttpStatusCode.BadRequest, unknown.StatusCode);
        Assert.Equal(
            "unknown_class_type",
            (await unknown.Content.ReadFromJsonAsync<FailureBody>())!.Reason);

        var deactivate = await admin.PostAsJsonAsync($"{TypesEndpoint}/{type.Id}/deactivate", new { });
        Assert.Equal(HttpStatusCode.OK, deactivate.StatusCode);

        var inactive = await admin.PostAsJsonAsync(
            Endpoint, Request(type.Id, NextSlot(), trainerId));

        Assert.Equal(HttpStatusCode.BadRequest, inactive.StatusCode);
        Assert.Equal(
            "inactive_class_type",
            (await inactive.Content.ReadFromJsonAsync<FailureBody>())!.Reason);
    }

    [Fact]
    public async Task Editing_an_occurrence_whose_type_was_deactivated_still_works()
    {
        // FR-006 promises that deactivating a type leaves its existing occurrences intact — and an
        // occurrence the admin can no longer reschedule is not intact.
        var (admin, type, trainerId) = await ArrangeAsync();
        var slot = NextSlot();

        var created = await PostClassAsync(admin, type.Id, slot, trainerId);

        await admin.PostAsJsonAsync($"{TypesEndpoint}/{type.Id}/deactivate", new { });

        var edit = await admin.PutAsJsonAsync(
            $"{Endpoint}/{created.Id}", Request(type.Id, slot.AddHours(2), trainerId));

        Assert.Equal(HttpStatusCode.OK, edit.StatusCode);
        Assert.Equal(
            slot.AddHours(2),
            (await edit.Content.ReadFromJsonAsync<ClassBody>())!.StartsAt);
    }

    [Fact]
    public async Task Edit_refuses_a_change_of_class_type()
    {
        // Refused rather than silently ignored: a client sending a different type has a bug, and a
        // server that quietly discarded it would leave the admin believing they had changed something.
        var (admin, type, trainerId) = await ArrangeAsync();
        var slot = NextSlot();

        var created = await PostClassAsync(admin, type.Id, slot, trainerId);
        var otherType = await CreateTypeAsync(admin);

        var response = await admin.PutAsJsonAsync(
            $"{Endpoint}/{created.Id}", Request(otherType.Id, slot, trainerId));

        Assert.Equal(HttpStatusCode.BadRequest, response.StatusCode);
        Assert.Equal(
            "class_type_immutable",
            (await response.Content.ReadFromJsonAsync<FailureBody>())!.Reason);
    }

    // --- FR-009: the instructor is a person -----------------------------------

    [Fact]
    public async Task Create_refuses_an_instructor_who_is_not_a_trainer()
    {
        var (admin, type, _) = await ArrangeAsync();

        var memberId = await CreateAccountAsync(
            admin, AccountStatus.Active, ApplicationRoles.User);

        var response = await admin.PostAsJsonAsync(
            Endpoint, Request(type.Id, NextSlot(), memberId));

        Assert.Equal(HttpStatusCode.BadRequest, response.StatusCode);
        Assert.Equal(
            "instructor_not_trainer",
            (await response.Content.ReadFromJsonAsync<FailureBody>())!.Reason);
    }

    [Fact]
    public async Task Create_refuses_a_blocked_trainer_and_an_unknown_id()
    {
        var (admin, type, _) = await ArrangeAsync();

        var blockedTrainerId = await CreateAccountAsync(
            admin, AccountStatus.Blocked, ApplicationRoles.Trainer);

        var blocked = await admin.PostAsJsonAsync(
            Endpoint, Request(type.Id, NextSlot(), blockedTrainerId));

        Assert.Equal(HttpStatusCode.BadRequest, blocked.StatusCode);

        // Not a status of its own: the selection only ever offers active trainers, so an inactive id
        // means the client is working from a stale list. Telling the caller which accounts exist but
        // are blocked would leak account state onto a scheduling surface.
        Assert.Equal(
            "unknown_instructor",
            (await blocked.Content.ReadFromJsonAsync<FailureBody>())!.Reason);

        var unknown = await admin.PostAsJsonAsync(
            Endpoint, Request(type.Id, NextSlot(), Guid.NewGuid().ToString()));

        Assert.Equal(HttpStatusCode.BadRequest, unknown.StatusCode);
        Assert.Equal(
            "unknown_instructor",
            (await unknown.Content.ReadFromJsonAsync<FailureBody>())!.Reason);
    }

    [Fact]
    public async Task The_occurrence_resolves_the_instructors_display_name()
    {
        var (admin, type, trainerId) = await ArrangeAsync();

        var created = await PostClassAsync(admin, type.Id, NextSlot(), trainerId);

        var members = await admin.GetFromJsonAsync<List<MemberBody>>("/api/admin/members");
        var expected = members!.Single(m => m.Id == trainerId).DisplayName;

        Assert.Equal(trainerId, created.InstructorUserId);
        Assert.Equal(expected, created.Instructor);
    }

    [Fact]
    public async Task Edit_can_reassign_the_instructor()
    {
        // Unlike the type, the instructor IS mutable — reassigning a class is ordinary admin work.
        var (admin, type, trainerId) = await ArrangeAsync();
        var slot = NextSlot();

        var created = await PostClassAsync(admin, type.Id, slot, trainerId);

        // A distinct display name, or the stale-name assertion below could not tell the two apart -
        // every account the fixture creates is otherwise called "Test Trainer".
        var replacement = await CreateTrainerAsync(admin, $"Zastępstwo-{Guid.NewGuid():N}");

        var response = await admin.PutAsJsonAsync(
            $"{Endpoint}/{created.Id}", Request(type.Id, slot, replacement));

        Assert.Equal(HttpStatusCode.OK, response.StatusCode);

        var body = (await response.Content.ReadFromJsonAsync<ClassBody>())!;
        Assert.Equal(replacement, body.InstructorUserId);

        // AND the display name is the NEW trainer's, not the previous one's.
        //
        // This is the half that can regress silently. The handler builds its response from the
        // account the validation resolved, precisely because the tracked entity's Instructor
        // navigation still points at the PREVIOUS account after the id is reassigned - projecting
        // from that navigation would return a stale name with a correct id, and every other
        // assertion here would still pass.
        var members = await admin.GetFromJsonAsync<List<MemberBody>>("/api/admin/members");
        var expected = members!.Single(m => m.Id == replacement).DisplayName;

        Assert.Equal(expected, body.Instructor);
        Assert.NotEqual(created.Instructor, body.Instructor);
    }

    // --- the trainer list ------------------------------------------------------

    [Fact]
    public async Task Trainers_lists_active_trainers_only()
    {
        var admin = await AdminAsync();

        var activeTrainer = await CreateTrainerAsync(admin);
        var blockedTrainer = await CreateAccountAsync(
            admin, AccountStatus.Blocked, ApplicationRoles.Trainer);
        var plainMember = await CreateAccountAsync(
            admin, AccountStatus.Active, ApplicationRoles.User);

        var trainers = await admin.GetFromJsonAsync<List<TrainerBody>>("/api/admin/trainers");
        var ids = trainers!.Select(t => t.Id).ToHashSet();

        Assert.Contains(activeTrainer, ids);
        Assert.DoesNotContain(blockedTrainer, ids);
        Assert.DoesNotContain(plainMember, ids);
    }

    [Fact]
    public async Task Trainers_includes_an_account_holding_both_admin_and_trainer()
    {
        // prd-v2 FR-003: roles are additive, so an owner who teaches appears in the same selection as
        // everyone else. The grant goes through the real endpoint rather than the fixture, because
        // that is the path an admin actually takes.
        var admin = await AdminAsync();
        var ownerId = await CreateAccountAsync(admin, AccountStatus.Active, ApplicationRoles.Admin);

        var grant = await admin.PostAsJsonAsync(
            $"/api/admin/members/{ownerId}/roles/trainer", new { });

        Assert.Equal(HttpStatusCode.OK, grant.StatusCode);

        var trainers = await admin.GetFromJsonAsync<List<TrainerBody>>("/api/admin/trainers");

        Assert.Contains(ownerId, trainers!.Select(t => t.Id));
    }

    // --- validation ------------------------------------------------------------

    [Fact]
    public async Task Create_refuses_a_missing_reference()
    {
        var (admin, type, trainerId) = await ArrangeAsync();

        var noType = await admin.PostAsJsonAsync(
            Endpoint, Request(Guid.Empty, NextSlot(), trainerId));

        Assert.Equal(HttpStatusCode.BadRequest, noType.StatusCode);
        Assert.Equal("missing_field", (await noType.Content.ReadFromJsonAsync<FailureBody>())!.Reason);

        var noInstructor = await admin.PostAsJsonAsync(
            Endpoint, Request(type.Id, NextSlot(), string.Empty));

        Assert.Equal(HttpStatusCode.BadRequest, noInstructor.StatusCode);
        Assert.Equal(
            "missing_field",
            (await noInstructor.Content.ReadFromJsonAsync<FailureBody>())!.Reason);
    }

    [Theory]
    [InlineData(0, 12, "invalid_duration")]
    [InlineData(481, 12, "invalid_duration")]
    [InlineData(60, 0, "invalid_capacity")]
    [InlineData(60, 201, "invalid_capacity")]
    public async Task Create_enforces_the_numeric_bounds(int duration, int capacity, string reason)
    {
        var (admin, type, trainerId) = await ArrangeAsync();

        var response = await admin.PostAsJsonAsync(
            Endpoint, Request(type.Id, NextSlot(), trainerId, duration, capacity));

        Assert.Equal(HttpStatusCode.BadRequest, response.StatusCode);
        Assert.Equal(reason, (await response.Content.ReadFromJsonAsync<FailureBody>())!.Reason);
    }

    [Fact]
    public async Task Create_refuses_a_start_in_the_past_but_edit_does_not()
    {
        var (admin, type, trainerId) = await ArrangeAsync();

        var past = await admin.PostAsJsonAsync(
            Endpoint,
            Request(type.Id, DateTimeOffset.UtcNow.AddDays(-1), trainerId));

        Assert.Equal(HttpStatusCode.BadRequest, past.StatusCode);
        Assert.Equal("starts_in_past", (await past.Content.ReadFromJsonAsync<FailureBody>())!.Reason);

        // Correcting a class that already ran is legitimate; refusing it would leave a wrong record
        // permanently wrong. Slots are 60 days apart, so a past time cannot collide with another test.
        var created = await PostClassAsync(admin, type.Id, NextSlot(), trainerId);

        var edit = await admin.PutAsJsonAsync(
            $"{Endpoint}/{created.Id}",
            Request(type.Id, new DateTimeOffset(2020, 1, 1, 10, 0, 0, TimeSpan.Zero), trainerId));

        Assert.Equal(HttpStatusCode.OK, edit.StatusCode);
    }

    // --- the member's view -----------------------------------------------------

    [Fact]
    public async Task The_member_schedule_resolves_the_name_and_instructor_too()
    {
        // The member window is a fortnight, so this one class is created near "now" rather than in a
        // 2030 slot — and therefore has to dodge the other tests' classes by using a time no slot
        // covers.
        var (admin, type, trainerId) = await ArrangeAsync();
        var soon = DateTimeOffset.UtcNow.AddDays(3);

        var created = await PostClassAsync(admin, type.Id, soon, trainerId);

        var member = await fixture.CreateAuthenticatedClientAsync(TestUsers.ActiveMemberEmail);
        var schedule = await member.GetFromJsonAsync<List<ClassBody>>("/api/classes");

        var row = schedule!.Single(c => c.Id == created.Id);

        Assert.Equal(type.Name, row.Name);
        Assert.Equal("Opis", row.Description);
        Assert.NotEmpty(row.Instructor);

        // FreeSpots is capacity by construction until Booking exists (S-08).
        Assert.Equal(row.Capacity, row.FreeSpots);
    }
}
