using Microsoft.Extensions.Options;
using po_prostu_silka.Domain;
using po_prostu_silka.Domain.Notifications;

namespace po_prostu_silka.Application.Notifications;

/// <summary>
/// The password-reset email (S-13). Follows <see cref="AccountApprovedNotification"/> exactly:
/// rendered here at enqueue time, plain text, Polish copy, delivered by the outbox worker.
///
/// <para>
/// EMAIL ONLY, NOT EMAIL + PUSH. Every other notification in this app fans out to the member's push
/// subscriptions too. This one must not: a reset has to reach the address being recovered, and a
/// push subscription is a device — possibly one the person asking does not own, and possibly one
/// still subscribed after the account changed hands. The whole point of the flow is that possession
/// of the mailbox is the proof.
/// </para>
/// </summary>
public interface IPasswordResetNotification
{
    /// <summary>
    /// Enqueues the reset email. Does NOT save — the caller owns the unit of work, exactly like
    /// <see cref="IOutboxEnqueuer"/>.
    /// </summary>
    /// <param name="member">The account being recovered.</param>
    /// <param name="token">A token already generated by <c>GeneratePasswordResetTokenAsync</c>.
    /// Generated by the caller rather than here, so this type stays free of Identity.</param>
    void Notify(ApplicationUser member, string token);
}

public class PasswordResetNotification(
    IOutboxEnqueuer enqueuer,
    IOptions<AppOptions> appOptions,
    ILogger<PasswordResetNotification> logger) : IPasswordResetNotification
{
    private const string Subject = "Resetowanie hasła w Po Prostu Siłka";

    private readonly AppOptions app = appOptions.Value;

    public void Notify(ApplicationUser member, string token)
    {
        if (string.IsNullOrWhiteSpace(member.Email))
        {
            return;
        }

        if (!app.IsConfigured)
        {
            // Logged and dropped, never surfaced. The caller answers identically either way — see
            // ForgotPasswordAsync. A misconfigured deployment produces silent non-delivery, which is
            // strictly better than a response shape that reveals which addresses are registered.
            logger.LogError(
                "Password reset email not enqueued: {Section}:BaseUrl is not configured, so no "
                + "usable link can be built. Set the App__BaseUrl application setting.",
                AppOptions.SectionName);
            return;
        }

        // QUERY STRING, NOT A PATH SEGMENT. Identity's tokens are base64 and routinely contain '+'
        // and '/'; in a path segment those are either re-interpreted or normalised away by the
        // server before the SPA ever sees them, and the token arrives corrupt. As a query value,
        // percent-encoding survives the round trip.
        var link =
            $"{app.BaseUrl.TrimEnd('/')}/reset-password"
            + $"?email={Uri.EscapeDataString(member.Email)}"
            + $"&token={Uri.EscapeDataString(token)}";

        var name = string.IsNullOrWhiteSpace(member.DisplayName) ? "Cześć" : member.DisplayName;

        // Plain text and interpolation, like every other body here. The link sits on its own line so
        // mail clients linkify it cleanly and it survives being copied by hand.
        var body =
            $"{name}, otrzymaliśmy prośbę o zresetowanie hasła do Twojego konta w Po Prostu Siłka.\n\n"
            + "Kliknij poniższy link, aby ustawić nowe hasło:\n\n"
            + $"{link}\n\n"
            + "Link jest ważny przez 24 godziny i można go użyć tylko raz.\n\n"
            + "Jeśli to nie Ty prosiłeś o zmianę hasła, zignoruj tę wiadomość - Twoje hasło "
            + "pozostanie bez zmian.";

        enqueuer.Enqueue(NotificationChannel.Email, member.Email, Subject, body);
    }
}
